# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import db_pb2 as db__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class DBStub(object):
  """In memory DB definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Search = channel.unary_unary(
        '/db.DB/Search',
        request_serializer=db__pb2.Value.SerializeToString,
        response_deserializer=db__pb2.Records.FromString,
        )
    self.Add = channel.unary_unary(
        '/db.DB/Add',
        request_serializer=db__pb2.Value.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.Update = channel.unary_unary(
        '/db.DB/Update',
        request_serializer=db__pb2.Records.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class DBServicer(object):
  """In memory DB definition.
  """

  def Search(self, request, context):
    """Search record.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Add(self, request, context):
    """Add record.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Update(self, request, context):
    """Update record.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DBServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Search': grpc.unary_unary_rpc_method_handler(
          servicer.Search,
          request_deserializer=db__pb2.Value.FromString,
          response_serializer=db__pb2.Records.SerializeToString,
      ),
      'Add': grpc.unary_unary_rpc_method_handler(
          servicer.Add,
          request_deserializer=db__pb2.Value.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'Update': grpc.unary_unary_rpc_method_handler(
          servicer.Update,
          request_deserializer=db__pb2.Records.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'db.DB', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
