# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='db.proto',
  package='db',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x08\x64\x62.proto\x12\x02\x64\x62\x1a\x1bgoogle/protobuf/empty.proto\"&\n\x07Records\x12\x1b\n\x07records\x18\x01 \x03(\x0b\x32\n.db.Record\"&\n\x06Record\x12\r\n\x05index\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05\"\x16\n\x05Value\x12\r\n\x05value\x18\x01 \x01(\x05\x32\x85\x01\n\x02\x44\x42\x12\"\n\x06Search\x12\t.db.Value\x1a\x0b.db.Records\"\x00\x12*\n\x03\x41\x64\x64\x12\t.db.Value\x1a\x16.google.protobuf.Empty\"\x00\x12/\n\x06Update\x12\x0b.db.Records\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_RECORDS = _descriptor.Descriptor(
  name='Records',
  full_name='db.Records',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='records', full_name='db.Records.records', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=83,
)


_RECORD = _descriptor.Descriptor(
  name='Record',
  full_name='db.Record',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='db.Record.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='db.Record.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=123,
)


_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='db.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='db.Value.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=147,
)

_RECORDS.fields_by_name['records'].message_type = _RECORD
DESCRIPTOR.message_types_by_name['Records'] = _RECORDS
DESCRIPTOR.message_types_by_name['Record'] = _RECORD
DESCRIPTOR.message_types_by_name['Value'] = _VALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Records = _reflection.GeneratedProtocolMessageType('Records', (_message.Message,), {
  'DESCRIPTOR' : _RECORDS,
  '__module__' : 'db_pb2'
  # @@protoc_insertion_point(class_scope:db.Records)
  })
_sym_db.RegisterMessage(Records)

Record = _reflection.GeneratedProtocolMessageType('Record', (_message.Message,), {
  'DESCRIPTOR' : _RECORD,
  '__module__' : 'db_pb2'
  # @@protoc_insertion_point(class_scope:db.Record)
  })
_sym_db.RegisterMessage(Record)

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), {
  'DESCRIPTOR' : _VALUE,
  '__module__' : 'db_pb2'
  # @@protoc_insertion_point(class_scope:db.Value)
  })
_sym_db.RegisterMessage(Value)



_DB = _descriptor.ServiceDescriptor(
  name='DB',
  full_name='db.DB',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=150,
  serialized_end=283,
  methods=[
  _descriptor.MethodDescriptor(
    name='Search',
    full_name='db.DB.Search',
    index=0,
    containing_service=None,
    input_type=_VALUE,
    output_type=_RECORDS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Add',
    full_name='db.DB.Add',
    index=1,
    containing_service=None,
    input_type=_VALUE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='db.DB.Update',
    index=2,
    containing_service=None,
    input_type=_RECORDS,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DB)

DESCRIPTOR.services_by_name['DB'] = _DB

# @@protoc_insertion_point(module_scope)
