[package]
name = "rust"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
rand  = "0.7"
tonic = "0.1"
prost = "0.6"
tokio = { version = "0.2", features = ["macros"] }

[build-dependencies]
tonic-build = "0.1.0"
